package com.app.domain.net.data;

/**
 * Created by lijian15 on 2016/12/14.
 */

public class ConstData {
    /** The key that generated by Google Translate API */
    public final static String GOOGLE_APP_KEY = "AIzaSyCh5D3AoioKz7H-UQhq-J40ac8tzv6YVpk";

    /** Base url */
    public final static String GOOGLE_TRANS_URL = "https://www.googleapis.com/language/translate/v2?";

    /** Url for patch of hot-fix */
    public final static String HOT_PATCH_URL = "http://storage.jd.com/wxapp/patch_signed_7zip.apk";

    public final static String KEY_FUNCTION_ID = "functionId";

    public final static String FUNCTION_ID_TEST = "addresspdj/getAddressList";
}
