package com.app.domain.net.data;

/**
 * Created by lijian15 on 2016/12/14.
 */

public class ConstData {
    /** The key that generated by Google Translate API */
    public final static String GOOGLE_APP_KEY = "AIzaSyCh5D3AoioKz7H-UQhq-J40ac8tzv6YVpk";

    /** Base url */
    public final static String GOOGLE_TRANS_URL = "https://www.googleapis.com/language/translate/v2?";

    /** Url for patch of hot-fix */
    public final static String HOT_PATCH_URL = "http://storage.jd.com/wxapp/patch_signed_7zip.apk";

    public final static String KEY_FUNCTION_ID = "functionId";

    public final static String FUNCTION_ID_TEST = "addresspdj/getAddressList";

    public final static String HOST = "http://api.china1896.com";

    /** 登录模块获取短信验证码接口，注册 */
    public final static int REQUEST_SMS_TYPE_REGISTER = 1;

    /** 登录模块获取短信验证码接口，修改密码 */
    public final static int REQUEST_SMS_TYPE_MODIFY_PASS = 2;

    /** 登录模块获取短信验证码token */
    public final static String LOGIN_SMS_TOKEN = "XQBYdcHKSO+RS16jQhf+cRYJqaerqCole";

    /** 注册用户类型 */
    public final static String REGISTER_USER_TYPE = "5";

    /** 分页，每页条数 */
    public final static int DEFAULT_PAGE_SIZE = 10;

    /** 无效的名家id */
    public final static int INVALID_CELEBRITY_ID = -1;

    /** 观看历史 */
    public final static String FUNCTION_ID_MY_HISTORY = "/Special/Special/getUserHistory";

    /** 我的收藏 */
    public final static String FUNCTION_ID_MY_FAVORITE = "/Special/Special/getUserCollect";

    /** 消息类型：评论 */
    public final static String MESSAGE_TYPE_COMMENT = "2";

    /** 消息类型：点赞 */
    public final static String MESSAGE_TYPE_NB = "3";
}
