package com.translatmaster.data;

/**
 * Created by lijian15 on 2016/12/14.
 */

public class ConstData {
    /** The key that generated by Google Translate API */
    public final static String GOOTLE_APP_KEY = "AIzaSyCh5D3AoioKz7H-UQhq-J40ac8tzv6YVpk";

    /** Base url */
    public final static String GOOGLE_TRANS_URL = "https://www.googleapis.com/language/translate/v2?";
}
